export const SET_DATA_MOVIES = 'SET_DATA_MOVIES';
export const SET_CHARACTER_ID = 'SET_CHARACTER_ID';
export const SET_DATA_FAVORITE_MOVIES = 'SET_DATA_FAVORITE_MOVIES';
export const SET_REMOVE_FAVORITE_MOVIES = 'SET_REMOVE_FAVORITE_MOVIES';
